/*
* This file was generated by the CommonAPI Generators. 
* Used org.genivi.commonapi.core 2.1.2.201309301424.
* Used org.franca.core 0.8.10.201309262002.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef ORG_GENIVI_PROFILE_MGMT_CTRL_Profile_Manager_Ctrl_Consumer_DBUS_PROXY_H_
#define ORG_GENIVI_PROFILE_MGMT_CTRL_Profile_Manager_Ctrl_Consumer_DBUS_PROXY_H_

#include <org/genivi/profile_mgmt_ctrl/ProfileManagerCtrlConsumerProxyBase.h>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/DBus/DBusFactory.h>
#include <CommonAPI/DBus/DBusProxy.h>

#undef COMMONAPI_INTERNAL_COMPILATION

#include <string>

namespace org {
namespace genivi {
namespace profile_mgmt_ctrl {

class ProfileManagerCtrlConsumerDBusProxy: virtual public ProfileManagerCtrlConsumerProxyBase, virtual public CommonAPI::DBus::DBusProxy {
 public:
    ProfileManagerCtrlConsumerDBusProxy(
                    const std::shared_ptr<CommonAPI::DBus::DBusFactory>& factory,
                    const std::string& commonApiAddress,
                    const std::string& interfaceName,
                    const std::string& busName,
                    const std::string& objectPath,
                    const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection>& dbusProxyconnection);

    virtual ~ProfileManagerCtrlConsumerDBusProxy() { }



    virtual void onTimeOut(const std::string& appName, const uint32_t& userId, const uint32_t& seatId, const ProfileManagerCtrlConsumer::ESignal& s, const uint64_t& sessionId, const int32_t& timeElapsedMs, const uint64_t& timeOutSessionId, CommonAPI::CallStatus& callStatus);
    virtual std::future<CommonAPI::CallStatus> onTimeOutAsync(const std::string& appName, const uint32_t& userId, const uint32_t& seatId, const ProfileManagerCtrlConsumer::ESignal& s, const uint64_t& sessionId, const int32_t& timeElapsedMs, const uint64_t& timeOutSessionId, OnTimeOutAsyncCallback callback);
    virtual void onStateChangeStart(const uint32_t& userId, const uint32_t& seatId, const int32_t& depLevel, const ProfileManagerCtrlConsumer::ESignal& s, const uint64_t& sessionId, CommonAPI::CallStatus& callStatus);
    virtual std::future<CommonAPI::CallStatus> onStateChangeStartAsync(const uint32_t& userId, const uint32_t& seatId, const int32_t& depLevel, const ProfileManagerCtrlConsumer::ESignal& s, const uint64_t& sessionId, OnStateChangeStartAsyncCallback callback);
    virtual void onStateChangeStop(const uint32_t& userId, const uint32_t& seatId, const int32_t& depLevel, const ProfileManagerCtrlConsumer::ESignal& s, const uint64_t& sessionId, CommonAPI::CallStatus& callStatus);
    virtual std::future<CommonAPI::CallStatus> onStateChangeStopAsync(const uint32_t& userId, const uint32_t& seatId, const int32_t& depLevel, const ProfileManagerCtrlConsumer::ESignal& s, const uint64_t& sessionId, OnStateChangeStopAsyncCallback callback);
    virtual void onClientRegister(const std::string& appName, const uint32_t& seatId, CommonAPI::CallStatus& callStatus);
    virtual std::future<CommonAPI::CallStatus> onClientRegisterAsync(const std::string& appName, const uint32_t& seatId, OnClientRegisterAsyncCallback callback);
    virtual void onClientUnregister(const std::string& appName, const uint32_t& seatId, CommonAPI::CallStatus& callStatus);
    virtual std::future<CommonAPI::CallStatus> onClientUnregisterAsync(const std::string& appName, const uint32_t& seatId, OnClientUnregisterAsyncCallback callback);
    

    virtual void getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const;

 private:

    
};



} // namespace profile_mgmt_ctrl
} // namespace genivi
} // namespace org

#endif // ORG_GENIVI_PROFILE_MGMT_CTRL_Profile_Manager_Ctrl_Consumer_DBUS_PROXY_H_
