/*
* This file was generated by the CommonAPI Generators. 
* Used org.genivi.commonapi.core 2.1.4.201311151436.
* Used org.franca.core 0.8.11.201401091023.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include "ProfileManagerCtrlDBusProxy.h"

namespace org {
namespace genivi {
namespace profile_mgmt_ctrl {

std::shared_ptr<CommonAPI::DBus::DBusProxy> createProfileManagerCtrlDBusProxy(
                    const std::shared_ptr<CommonAPI::DBus::DBusFactory>& factory,
                    const std::string& commonApiAddress,
                    const std::string& interfaceName,
                    const std::string& busName,
                    const std::string& objectPath,
                    const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection>& dbusProxyConnection) {
    return std::make_shared<ProfileManagerCtrlDBusProxy>(factory, commonApiAddress, interfaceName, busName, objectPath, dbusProxyConnection);
}

__attribute__((constructor)) void registerProfileManagerCtrlDBusProxy(void) {
    CommonAPI::DBus::DBusFactory::registerProxyFactoryMethod(ProfileManagerCtrl::getInterfaceId(),
       &createProfileManagerCtrlDBusProxy);
}

ProfileManagerCtrlDBusProxy::ProfileManagerCtrlDBusProxy(
                    const std::shared_ptr<CommonAPI::DBus::DBusFactory>& factory,
                    const std::string& commonApiAddress,
                    const std::string& interfaceName,
                    const std::string& busName,
                    const std::string& objectPath,
                    const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection>& dbusProxyconnection):
        CommonAPI::DBus::DBusProxy(factory, commonApiAddress, interfaceName, busName, objectPath, dbusProxyconnection)
,        onTimeOutSelective_(*this, "onTimeOut", "suuitit"),
        onStateChangeStartSelective_(*this, "onStateChangeStart", "uuiit"),
        onStateChangeStopSelective_(*this, "onStateChangeStop", "uuiit"),
        onClientRegisterSelective_(*this, "onClientRegister", "su"),
        onClientUnregisterSelective_(*this, "onClientUnregister", "su")
    {
    }


ProfileManagerCtrlDBusProxy::OnTimeOutSelectiveEvent& ProfileManagerCtrlDBusProxy::getOnTimeOutSelectiveEvent() {
    return onTimeOutSelective_;
}
ProfileManagerCtrlDBusProxy::OnStateChangeStartSelectiveEvent& ProfileManagerCtrlDBusProxy::getOnStateChangeStartSelectiveEvent() {
    return onStateChangeStartSelective_;
}
ProfileManagerCtrlDBusProxy::OnStateChangeStopSelectiveEvent& ProfileManagerCtrlDBusProxy::getOnStateChangeStopSelectiveEvent() {
    return onStateChangeStopSelective_;
}
ProfileManagerCtrlDBusProxy::OnClientRegisterSelectiveEvent& ProfileManagerCtrlDBusProxy::getOnClientRegisterSelectiveEvent() {
    return onClientRegisterSelective_;
}
ProfileManagerCtrlDBusProxy::OnClientUnregisterSelectiveEvent& ProfileManagerCtrlDBusProxy::getOnClientUnregisterSelectiveEvent() {
    return onClientUnregisterSelective_;
}

void ProfileManagerCtrlDBusProxy::registerMe(const bool& registerOnTimeOut, const bool& registerOnStateChangeStart, const bool& registerOnStateChangeStop, const bool& registerOnClientRegister, const bool& registerOnClientUnregister, CommonAPI::CallStatus& callStatus) {
    CommonAPI::DBus::DBusProxyHelper<CommonAPI::DBus::DBusSerializableArguments<bool, bool, bool, bool, bool>,
                                     CommonAPI::DBus::DBusSerializableArguments<> >::callMethodWithReply(
        *this,
        "registerMe",
        "bbbbb",
        registerOnTimeOut, registerOnStateChangeStart, registerOnStateChangeStop, registerOnClientRegister, registerOnClientUnregister, 
        callStatus
        );
}
std::future<CommonAPI::CallStatus> ProfileManagerCtrlDBusProxy::registerMeAsync(const bool& registerOnTimeOut, const bool& registerOnStateChangeStart, const bool& registerOnStateChangeStop, const bool& registerOnClientRegister, const bool& registerOnClientUnregister, RegisterMeAsyncCallback callback) {
    return CommonAPI::DBus::DBusProxyHelper<CommonAPI::DBus::DBusSerializableArguments<bool, bool, bool, bool, bool>,
                                     CommonAPI::DBus::DBusSerializableArguments<> >::callMethodAsync(
        *this,
        "registerMe",
        "bbbbb",
        registerOnTimeOut, registerOnStateChangeStart, registerOnStateChangeStop, registerOnClientRegister, registerOnClientUnregister, 
        std::move(callback));
}
void ProfileManagerCtrlDBusProxy::setUser(const uint32_t& userId, const uint32_t& seatId, CommonAPI::CallStatus& callStatus) {
    CommonAPI::DBus::DBusProxyHelper<CommonAPI::DBus::DBusSerializableArguments<uint32_t, uint32_t>,
                                     CommonAPI::DBus::DBusSerializableArguments<> >::callMethodWithReply(
        *this,
        "setUser",
        "uu",
        userId, seatId, 
        callStatus
        );
}
std::future<CommonAPI::CallStatus> ProfileManagerCtrlDBusProxy::setUserAsync(const uint32_t& userId, const uint32_t& seatId, SetUserAsyncCallback callback) {
    return CommonAPI::DBus::DBusProxyHelper<CommonAPI::DBus::DBusSerializableArguments<uint32_t, uint32_t>,
                                     CommonAPI::DBus::DBusSerializableArguments<> >::callMethodAsync(
        *this,
        "setUser",
        "uu",
        userId, seatId, 
        std::move(callback));
}
void ProfileManagerCtrlDBusProxy::unsetUser(const uint32_t& seatId, CommonAPI::CallStatus& callStatus) {
    CommonAPI::DBus::DBusProxyHelper<CommonAPI::DBus::DBusSerializableArguments<uint32_t>,
                                     CommonAPI::DBus::DBusSerializableArguments<> >::callMethodWithReply(
        *this,
        "unsetUser",
        "u",
        seatId, 
        callStatus
        );
}
std::future<CommonAPI::CallStatus> ProfileManagerCtrlDBusProxy::unsetUserAsync(const uint32_t& seatId, UnsetUserAsyncCallback callback) {
    return CommonAPI::DBus::DBusProxyHelper<CommonAPI::DBus::DBusSerializableArguments<uint32_t>,
                                     CommonAPI::DBus::DBusSerializableArguments<> >::callMethodAsync(
        *this,
        "unsetUser",
        "u",
        seatId, 
        std::move(callback));
}
void ProfileManagerCtrlDBusProxy::timeOutAction(const uint64_t& timeOutSessionId, const ProfileManagerCtrl::ETimeOutAction& timeOutActionItem, CommonAPI::CallStatus& callStatus) {
    CommonAPI::DBus::DBusProxyHelper<CommonAPI::DBus::DBusSerializableArguments<uint64_t, ProfileManagerCtrl::ETimeOutAction>,
                                     CommonAPI::DBus::DBusSerializableArguments<> >::callMethodWithReply(
        *this,
        "timeOutAction",
        "ti",
        timeOutSessionId, timeOutActionItem, 
        callStatus
        );
}
std::future<CommonAPI::CallStatus> ProfileManagerCtrlDBusProxy::timeOutActionAsync(const uint64_t& timeOutSessionId, const ProfileManagerCtrl::ETimeOutAction& timeOutActionItem, TimeOutActionAsyncCallback callback) {
    return CommonAPI::DBus::DBusProxyHelper<CommonAPI::DBus::DBusSerializableArguments<uint64_t, ProfileManagerCtrl::ETimeOutAction>,
                                     CommonAPI::DBus::DBusSerializableArguments<> >::callMethodAsync(
        *this,
        "timeOutAction",
        "ti",
        timeOutSessionId, timeOutActionItem, 
        std::move(callback));
}



void ProfileManagerCtrlDBusProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 1;
    ownVersionMinor = 0;
}

} // namespace profile_mgmt_ctrl
} // namespace genivi
} // namespace org
