/*
* This file was generated by the CommonAPI Generators. 
* Used org.genivi.commonapi.core 2.1.4.201311151436.
* Used org.franca.core 0.8.11.201401091023.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <org/genivi/profile_mgmt/ProfileManagerStubDefault.h>

namespace org {
namespace genivi {
namespace profile_mgmt {

ProfileManagerStubDefault::ProfileManagerStubDefault():
        remoteEventHandler_(this) {
}

ProfileManagerStubRemoteEvent* ProfileManagerStubDefault::initStubAdapter(const std::shared_ptr<ProfileManagerStubAdapter>& stubAdapter) {
    stubAdapter_ = stubAdapter;
    return &remoteEventHandler_;
}


void ProfileManagerStubDefault::registerMe(const std::shared_ptr<CommonAPI::ClientId> clientId, std::string appID, int32_t seatID) {
    // Call old style methods in default 
    registerMe(appID, seatID);
}
void ProfileManagerStubDefault::registerMe(std::string appID, int32_t seatID) {
    // No operation in default
}

void ProfileManagerStubDefault::unregisterMe(const std::shared_ptr<CommonAPI::ClientId> clientId, std::string consumerAddress, std::string appID, int32_t seatID) {
    // Call old style methods in default 
    unregisterMe(consumerAddress, appID, seatID);
}
void ProfileManagerStubDefault::unregisterMe(std::string consumerAddress, std::string appID, int32_t seatID) {
    // No operation in default
}

void ProfileManagerStubDefault::confirm(const std::shared_ptr<CommonAPI::ClientId> clientId, uint64_t sessionID) {
    // Call old style methods in default 
    confirm(sessionID);
}
void ProfileManagerStubDefault::confirm(uint64_t sessionID) {
    // No operation in default
}

void ProfileManagerStubDefault::stopped(const std::shared_ptr<CommonAPI::ClientId> clientId, uint64_t sessionID) {
    // Call old style methods in default 
    stopped(sessionID);
}
void ProfileManagerStubDefault::stopped(uint64_t sessionID) {
    // No operation in default
}


void ProfileManagerStubDefault::fireDetectedUserSelective(const int32_t& seatID, const int32_t& userID, const uint64_t& sessionID, const std::shared_ptr<CommonAPI::ClientIdList> receivers) {
    stubAdapter_->sendDetectedUserSelective(seatID, userID, sessionID, receivers);
}
void ProfileManagerStubDefault::onDetectedUserSelectiveSubscriptionChanged(const std::shared_ptr<CommonAPI::ClientId> clientId, const CommonAPI::SelectiveBroadcastSubscriptionEvent event) {
    // No operation in default
}
bool ProfileManagerStubDefault::onDetectedUserSelectiveSubscriptionRequested(const std::shared_ptr<CommonAPI::ClientId> clientId) {
    // Accept in default
    return true;
}
std::shared_ptr<CommonAPI::ClientIdList> const ProfileManagerStubDefault::getSubscribersForDetectedUserSelective() {
    return(stubAdapter_->getSubscribersForDetectedUserSelective());
}

void ProfileManagerStubDefault::fireSynchronizedUserSelective(const int32_t& seatID, const int32_t& userID, const uint64_t& sessionID, const std::shared_ptr<CommonAPI::ClientIdList> receivers) {
    stubAdapter_->sendSynchronizedUserSelective(seatID, userID, sessionID, receivers);
}
void ProfileManagerStubDefault::onSynchronizedUserSelectiveSubscriptionChanged(const std::shared_ptr<CommonAPI::ClientId> clientId, const CommonAPI::SelectiveBroadcastSubscriptionEvent event) {
    // No operation in default
}
bool ProfileManagerStubDefault::onSynchronizedUserSelectiveSubscriptionRequested(const std::shared_ptr<CommonAPI::ClientId> clientId) {
    // Accept in default
    return true;
}
std::shared_ptr<CommonAPI::ClientIdList> const ProfileManagerStubDefault::getSubscribersForSynchronizedUserSelective() {
    return(stubAdapter_->getSubscribersForSynchronizedUserSelective());
}

void ProfileManagerStubDefault::fireStopSelective(const int32_t& seatID, const uint64_t& sessionID, const std::shared_ptr<CommonAPI::ClientIdList> receivers) {
    stubAdapter_->sendStopSelective(seatID, sessionID, receivers);
}
void ProfileManagerStubDefault::onStopSelectiveSubscriptionChanged(const std::shared_ptr<CommonAPI::ClientId> clientId, const CommonAPI::SelectiveBroadcastSubscriptionEvent event) {
    // No operation in default
}
bool ProfileManagerStubDefault::onStopSelectiveSubscriptionRequested(const std::shared_ptr<CommonAPI::ClientId> clientId) {
    // Accept in default
    return true;
}
std::shared_ptr<CommonAPI::ClientIdList> const ProfileManagerStubDefault::getSubscribersForStopSelective() {
    return(stubAdapter_->getSubscribersForStopSelective());
}



ProfileManagerStubDefault::RemoteEventHandler::RemoteEventHandler(ProfileManagerStubDefault* defaultStub):
        defaultStub_(defaultStub) {
}

} // namespace profile_mgmt
} // namespace genivi
} // namespace org
