/*****************************************************************
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0. If a copy of the MPL was not distributed with this file,
* You can obtain one at http://mozilla.org/MPL/2.0/.
* Copyright (c) 2012 Harman International Industries, Inc.
* All rights reserved
****************************************************************/
#ifndef PROFILEMANAGERSTUB_H_
#define PROFILEMANAGERSTUB_H_

//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
//This file is used temporarily to reflect the CommonAPI files to be generated.
//This file should vanish, once CommonAPI generation is available.
//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#include "CommonApi.h"

/**
 * ProfileManager.fidl stub as it should be generated by CommonAPI generator
 */
class ProfileManagerStub : public CommonAPI::Stub{
public:
   ProfileManagerStub(): Stub(){};
   virtual ~ProfileManagerStub(){};

   virtual void registerMe (std::string consumerAddress, std::string appID, int32_t seatID) = 0;

   virtual void unregisterMe (std::string consumerAddress, std::string appID, int32_t seatID) = 0;

   virtual void confirm(uint64_t sessionID) = 0;

   virtual void stopped(uint64_t sessionID) = 0;

};


#endif /* PROFILEMANAGERSTUB_H_ */
