/*
* This file was generated by the CommonAPI Generators. 
* Used org.genivi.commonapi.core 2.1.2.201309301424.
* Used org.franca.core 0.8.10.201309262002.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef ORG_GENIVI_PROFILE_MGMT_Profile_Manager_H_
#define ORG_GENIVI_PROFILE_MGMT_Profile_Manager_H_



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/types.h>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace org {
namespace genivi {
namespace profile_mgmt {

class ProfileManager {
 public:
    virtual ~ProfileManager() { }

    static inline const char* getInterfaceId();
    static inline CommonAPI::Version getInterfaceVersion();
};

const char* ProfileManager::getInterfaceId() {
    static const char* interfaceId = "org.genivi.profile_mgmt.ProfileManager";
    return interfaceId;
}

CommonAPI::Version ProfileManager::getInterfaceVersion() {
    return CommonAPI::Version(1, 0);
}


} // namespace profile_mgmt
} // namespace genivi
} // namespace org

namespace CommonAPI {

}


namespace std {
    //hashes for types
    
    //hashes for error types
}

#endif // ORG_GENIVI_PROFILE_MGMT_Profile_Manager_H_
