/*
* This file was generated by the CommonAPI Generators. 
* Used org.genivi.commonapi.core 2.1.2.201309301424.
* Used org.franca.core 0.8.10.201309262002.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef ORG_GENIVI_PROFILE_MGMT_Profile_Manager_Consumer_PROXY_H_
#define ORG_GENIVI_PROFILE_MGMT_Profile_Manager_Consumer_PROXY_H_

#include "ProfileManagerConsumerProxyBase.h"

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif


#undef COMMONAPI_INTERNAL_COMPILATION

namespace org {
namespace genivi {
namespace profile_mgmt {

template <typename ... _AttributeExtensions>
class ProfileManagerConsumerProxy: virtual public ProfileManagerConsumer, virtual public ProfileManagerConsumerProxyBase, public _AttributeExtensions... {
 public:
    ProfileManagerConsumerProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~ProfileManagerConsumerProxy();



    /**
     * Calls detectedUser with synchronous semantics.
     * 
    * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void detectedUser(const int32_t& seatID, const int32_t& userID, const uint64_t& sessionID, CommonAPI::CallStatus& callStatus);
    /**
     * Calls detectedUser with asynchronous semantics.
     * 
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> detectedUserAsync(const int32_t& seatID, const int32_t& userID, const uint64_t& sessionID, DetectedUserAsyncCallback callback);
    /**
     * Calls synchronizedUser with synchronous semantics.
     * 
    * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void synchronizedUser(const int32_t& seatID, const int32_t& userID, const uint64_t& sessionID, CommonAPI::CallStatus& callStatus);
    /**
     * Calls synchronizedUser with asynchronous semantics.
     * 
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> synchronizedUserAsync(const int32_t& seatID, const int32_t& userID, const uint64_t& sessionID, SynchronizedUserAsyncCallback callback);
    /**
     * Calls stop with synchronous semantics.
     * 
    * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void stop(const int32_t& seatID, const uint64_t& sessionID, CommonAPI::CallStatus& callStatus);
    /**
     * Calls stop with asynchronous semantics.
     * 
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> stopAsync(const int32_t& seatID, const uint64_t& sessionID, StopAsyncCallback callback);
    

    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual std::string getAddress() const;

    /**
     * Returns the domain of the remote partner this proxy communicates with.
     */
    virtual const std::string& getDomain() const;

    /** 
     * Returns the service ID of the remote partner this proxy communicates with.
     */
    virtual const std::string& getServiceId() const;

    /**
     * Returns the instance ID of the remote partner this proxy communicates with.
     */
    virtual const std::string& getInstanceId() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

 private:
    std::shared_ptr<ProfileManagerConsumerProxyBase> delegate_;
};


//
// ProfileManagerConsumerProxy Implementation
//
template <typename ... _AttributeExtensions>
ProfileManagerConsumerProxy<_AttributeExtensions...>::ProfileManagerConsumerProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        delegate_(std::dynamic_pointer_cast<ProfileManagerConsumerProxyBase>(delegate)),
        _AttributeExtensions(*(std::dynamic_pointer_cast<ProfileManagerConsumerProxyBase>(delegate)))... {
}

template <typename ... _AttributeExtensions>
ProfileManagerConsumerProxy<_AttributeExtensions...>::~ProfileManagerConsumerProxy() {
}

template <typename ... _AttributeExtensions>
void ProfileManagerConsumerProxy<_AttributeExtensions...>::detectedUser(const int32_t& seatID, const int32_t& userID, const uint64_t& sessionID, CommonAPI::CallStatus& callStatus) {
    delegate_->detectedUser(seatID, userID, sessionID, callStatus);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ProfileManagerConsumerProxy<_AttributeExtensions...>::detectedUserAsync(const int32_t& seatID, const int32_t& userID, const uint64_t& sessionID, DetectedUserAsyncCallback callback) {
    return delegate_->detectedUserAsync(seatID, userID, sessionID, callback);
}
template <typename ... _AttributeExtensions>
void ProfileManagerConsumerProxy<_AttributeExtensions...>::synchronizedUser(const int32_t& seatID, const int32_t& userID, const uint64_t& sessionID, CommonAPI::CallStatus& callStatus) {
    delegate_->synchronizedUser(seatID, userID, sessionID, callStatus);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ProfileManagerConsumerProxy<_AttributeExtensions...>::synchronizedUserAsync(const int32_t& seatID, const int32_t& userID, const uint64_t& sessionID, SynchronizedUserAsyncCallback callback) {
    return delegate_->synchronizedUserAsync(seatID, userID, sessionID, callback);
}
template <typename ... _AttributeExtensions>
void ProfileManagerConsumerProxy<_AttributeExtensions...>::stop(const int32_t& seatID, const uint64_t& sessionID, CommonAPI::CallStatus& callStatus) {
    delegate_->stop(seatID, sessionID, callStatus);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ProfileManagerConsumerProxy<_AttributeExtensions...>::stopAsync(const int32_t& seatID, const uint64_t& sessionID, StopAsyncCallback callback) {
    return delegate_->stopAsync(seatID, sessionID, callback);
}

template <typename ... _AttributeExtensions>
std::string ProfileManagerConsumerProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
const std::string& ProfileManagerConsumerProxy<_AttributeExtensions...>::getDomain() const {
    return delegate_->getDomain();
}

template <typename ... _AttributeExtensions>
const std::string& ProfileManagerConsumerProxy<_AttributeExtensions...>::getServiceId() const {
    return delegate_->getServiceId();
}

template <typename ... _AttributeExtensions>
const std::string& ProfileManagerConsumerProxy<_AttributeExtensions...>::getInstanceId() const {
    return delegate_->getInstanceId();
}

template <typename ... _AttributeExtensions>
bool ProfileManagerConsumerProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool ProfileManagerConsumerProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& ProfileManagerConsumerProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& ProfileManagerConsumerProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}

        

} // namespace profile_mgmt
} // namespace genivi
} // namespace org


#endif // ORG_GENIVI_PROFILE_MGMT_Profile_Manager_Consumer_PROXY_H_
